import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "../../assets/css/index.css"
import AdminLayout from "@/components/Admin/AdminLayout";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Dashboard Spree Commerce",
    description: "Generated by create Spree Commerce",
    icons: {
        icon: "/LogoBlack.png", // đường dẫn tính từ /public
    },
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {

    return (
        <AdminLayout>{children}</AdminLayout>
    );
}

export default RootLayout
